### ISSUE TITLE
[Bug]: getting a lot of data from datastore casue this error

### ISSUE THREAD

**Issue by istrk33** [lenra-io/Lenra#107]
### What happened?

On my app when I try to get all data from a datastore, this error happened

### What browsers are you seeing the problem on?

Other (specify above)

### Version

beta

### Relevant log output

```Shell
`
08:27:47.719 [error] Application error (413) <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>PayloadTooLargeError: request entity too large<br> &nbsp; &nbsp;at IncomingMessage.onData (/home/app/node_modules/raw-body/index.js:253:12)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:314:20)<br> &nbsp; &nbsp;at addChunk (_stream_readable.js:297:12)<br> &nbsp; &nbsp;at readableAddChunk (_stream_readable.js:272:9)<br> &nbsp; &nbsp;at IncomingMessage.Readable.push (_stream_readable.js:213:10)<br> &nbsp; &nbsp;at HTTPParser.parserOnBody (_http_common.js:135:24)</pre>
</body>
</html>

08:27:47.719 [info] 2022/06/21 08:27:47 POST / - 413 Payload Too Large - ContentLength: 597

08:27:47.719 [info] POST / type: manifest 413 10.209 ms

08:27:47.720 [info] PayloadTooLargeError: request entity too large

08:27:47.721 [info]     at IncomingMessage.onData (/home/app/node_modules/raw-body/index.js:253:12)
    at IncomingMessage.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)

08:27:47.721 [info]     at IncomingMessage.Readable.push (_stream_readable.js:213:10)
    at HTTPParser.parserOnBody (_http_common.js:135:24)

08:27:47.719 [error] Task #PID<0.4440.0> started from #PID<0.4414.0> terminating
** (ArgumentError) argument error
    :erlang.++("Application error (413) <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>PayloadTooLargeError: request entity too large<br> &nbsp; &nbsp;at IncomingMessage.onData (/home/app/node_modules/raw-body/index.js:253:12)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:314:20)<br> &nbsp; &nbsp;at addChunk (_stream_readable.js:297:12)<br> &nbsp; &nbsp;at readableAddChunk (_stream_readable.js:272:9)<br> &nbsp; &nbsp;at IncomingMessage.Readable.push (_stream_readable.js:213:10)<br> &nbsp; &nbsp;at HTTPParser.parserOnBody (_http_common.js:135:24)</pre>\n</body>\n</html>\n", [])
    (application_runner 0.0.0-dev) lib/session/widget_cache.ex:288: ApplicationRunner.WidgetCache.build_comp_and_format/8
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (application_runner 0.0.0-dev) lib/session/widget_cache.ex:225: ApplicationRunner.WidgetCache.build_child_list/5
    (application_runner 0.0.0-dev) lib/session/widget_cache.ex:164: ApplicationRunner.WidgetCache.handle_component/5
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<1.53326239/0 in Parallel.map/2>
    Args: []
08:27:47.734 [error] GenServer #PID<0.4415.0> terminating
** (ArgumentError) argument error
    :erlang.++("Application error (413) <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>PayloadTooLargeError: request entity too large<br> &nbsp; &nbsp;at IncomingMessage.onData (/home/app/node_modules/raw-body/index.js:253:12)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:314:20)<br> &nbsp; &nbsp;at addChunk (_stream_readable.js:297:12)<br> &nbsp; &nbsp;at readableAddChunk (_stream_readable.js:272:9)<br> &nbsp; &nbsp;at IncomingMessage.Readable.push (_stream_readable.js:213:10)<br> &nbsp; &nbsp;at HTTPParser.parserOnBody (_http_common.js:135:24)</pre>\n</body>\n</html>\n", [])
    (application_runner 0.0.0-dev) lib/session/widget_cache.ex:288: ApplicationRunner.WidgetCache.build_comp_and_format/8
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (application_runner 0.0.0-dev) lib/session/widget_cache.ex:225: ApplicationRunner.WidgetCache.build_child_list/5
    (application_runner 0.0.0-dev) lib/session/widget_cache.ex:164: ApplicationRunner.WidgetCache.handle_component/5
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.4414.0>, {:badarg, [{:erlang, :++, ["Application error (413) <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>PayloadTooLargeError: request entity too large<br> &nbsp; &nbsp;at IncomingMessage.onData (/home/app/node_modules/raw-body/index.js:253:12)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:314:20)<br> &nbsp; &nbsp;at addChunk (_stream_readable.js:297:12)<br> &nbsp; &nbsp;at readableAddChunk (_stream_readable.js:272:9)<br> &nbsp; &nbsp;at IncomingMessage.Readable.push (_stream_readable.js:213:10)<br> &nbsp; &nbsp;at HTTPParser.parserOnBody (_http_common.js:135:24)</pre>\n</body>\n</html>\n", []], [error_info: %{module: :erl_erts_errors}]}, {ApplicationRunner.WidgetCache, :build_comp_and_format, 8, [file: 'lib/session/widget_cache.ex', line: 288]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 2385]}, {ApplicationRunner.WidgetCache, :build_child_list, 5, [file: 'lib/session/widget_cache.ex', line: 225]}, {ApplicationRunner.WidgetCache, :handle_component, 5, [file: 'lib/session/widget_cache.ex', line: 164]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 35]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
`
```

**Comment by Nesqwik** [comment]
We need to find a solution for big query result.
Improving the Openfaas max json request body size value is just pushing the limit further but not resolving this issue.
I only see two solutions : 
- Limit the size of the result. Above, the query just won't work and return a clean formatted error (not like this one)
   - With this solution, we can provide a pagination system to get the asked values using multiple queries.
- Allow potentially unlimited query result size and stream the result back.

Any more idea @taorepoara ?
